services:
  grafana:
    user: root
    container_name: db2-datasource
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-11.2.4-ubuntu}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp
      - 9090:9090/tcp
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/db2-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/db2-datasource
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.db2-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: db2-datasource
